version: '3.6'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-db

    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" 