version: '3.6'

services:
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-db

    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" 